name: Publish to Test PyPI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  test_pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - name: poetry config repo
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - name: poetry config token
        run: poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}
      - name: Publish package
        run: poetry publish --build -r testpypi

# from https://www.ianwootten.co.uk/2020/10/23/publishing-to-pypi-using-github-actions/
